### PR TITLE
Extend Near Cache test suite

### PR DESCRIPTION
**Pull request by mgencur**
* tests for stale reads
* tests with multiple clients

### CODE REVIEW

**Comment by mgencur** [comment]
@rigazilla , hmm, there are test failures which I did not see on localhost. But I suspect these are real issues. Not sure what I should change so as to make the tests pass.

**Comment by mgencur** [comment]
@rigazilla , The test was fixed.

**Comment by mgencur** [comment]
@rigazilla , the remaining test fails after this sequence:
`   cache1.Put(k, "v2");
    //Get needs to go remotely
    Assert.AreEqual("v2", cache2.Get(k)); //this still returns v1
`

**Comment by mgencur** [comment]
OK. I hope I've fixed the last test now. Let's wait for tests to finish.

**Comment by rigazilla** [comment]
Look good now. Merged thanks!

**Pull request merged**
