### PR TITLE
HRCPP-279 Refactor native test suite for C# client

### PR DESCRIPTION
**Pull request by mgencur**
https://issues.jboss.org/browse/HRCPP-279

The native test suite now runs two separate "test suites" - default and security. And the resulting xml files are TestResult-default.xml and TestResult-security.xml. This is because the server has to be started with different config file for each test suite, and to prevent starting the server before each test. So it only starts two times.

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 221](http://ci.infinispan.org/viewLog.html?buildId=40477&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 392b15d581ef2821cd9df4bd01faad853b8cd248
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:06:59

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 222](http://ci.infinispan.org/viewLog.html?buildId=40478&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 9db260b269a004877ddffd4b198afaaa69ee48b5
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:02:56

Process exited with code 255

**Comment by mgencur** [comment]
I removed one of the commits as it was causing troubles with latest snapshots.

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 242](http://ci.infinispan.org/viewLog.html?buildId=40607&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 2b3a863b497a4150245a723c9b97cb334f6be268
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:16

Process exited with code 255

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 243](http://ci.infinispan.org/viewLog.html?buildId=40608&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 2b3a863b497a4150245a723c9b97cb334f6be268
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:23

Process exited with code 255

**Comment by mgencur** [comment]
Retest this, please.

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 244](http://ci.infinispan.org/viewLog.html?buildId=40609&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 3c0a80b54cb812bb079420e536edd3924f19e47b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:14:44

**Comment by rigazilla** [comment]
@mgencur TeamCity says that it's all ok but it seems to me that the tests (query and ssl) fail. Have a look a the log

http://ci.infinispan.org/downloadBuildLog.html?buildId=40609

I'm trying to figure out why teamcity doesn't detect the error.

**Comment by mgencur** [comment]
There are now two result files: TestResult-default.xml and TestResult-security.xml  . Can CI be instructed to pick any TestResult*.xml  ?

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 248](http://ci.infinispan.org/viewLog.html?buildId=40645&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 3c0a80b54cb812bb079420e536edd3924f19e47b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:14:10

**Comment by mgencur** [comment]
I'll look why the tests are failing.

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 251](http://ci.infinispan.org/viewLog.html?buildId=40648&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 3c0a80b54cb812bb079420e536edd3924f19e47b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:12:42

Process exited with code 1

**Comment by mgencur** [comment]
Fixed the remaining tests. I had to add the proto2 files from your other PR. Now the build uses proto3 and the test uses proto2 for upload to the server.

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 253](http://ci.infinispan.org/viewLog.html?buildId=40861&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 13aabe09091432451976df94dd96022272ea0db8
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:13:55

**Comment by mgencur** [comment]
I squashed the commits into one.

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 254](http://ci.infinispan.org/viewLog.html?buildId=40881&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 2c1434161981699c21e1f3e3b31057b2a58c98c0
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:14:57

**Comment by rigazilla** [comment]
merged, thanks!

**Pull request merged**
