### PR TITLE
HRCPP-285 moved err detect to the right place

### PR DESCRIPTION
**Pull request by rigazilla**
Moved the goto statement outside the if.

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 247](http://ci.infinispan.org/viewLog.html?buildId=40640&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for e993167cc133f3972f0b4c6f79454928736a4565
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:14:22

**Comment by rigazilla** [comment]
@mgencur can you merge this? Should fix the test error detection by teamcity

**Comment by mgencur** [comment]
Merged.

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 250](http://ci.infinispan.org/viewLog.html?buildId=40647&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for e993167cc133f3972f0b4c6f79454928736a4565
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:11:12

Process exited with code 1

**Pull request closed without merging**
