### PR TITLE
HRCPP-269 Removed old Serializer classes

### PR DESCRIPTION
**Pull request by rigazilla**
Replaced the Serializer classes with the new Marshaller architecture

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 196](http://ci.infinispan.org/viewLog.html?buildId=39773&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 1cc89ea9454c8ba765f97c785132f4e1be7a23e8
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:20:15

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 213](http://ci.infinispan.org/viewLog.html?buildId=39984&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 1cc89ea9454c8ba765f97c785132f4e1be7a23e8
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:14:11

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 225](http://ci.infinispan.org/viewLog.html?buildId=40507&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 1cc89ea9454c8ba765f97c785132f4e1be7a23e8
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:11

Process exited with code 1

**Comment by mgencur** [comment]
Hi Vittorio, this PR looks good to me. I can integrate it when you fix the build and it runs fine.

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 235](http://ci.infinispan.org/viewLog.html?buildId=40520&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 1cc89ea9454c8ba765f97c785132f4e1be7a23e8
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:01

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 239](http://ci.infinispan.org/viewLog.html?buildId=40547&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 1cc89ea9454c8ba765f97c785132f4e1be7a23e8
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:14:31

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 245](http://ci.infinispan.org/viewLog.html?buildId=40613&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 1cc89ea9454c8ba765f97c785132f4e1be7a23e8
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:11

Process exited with code 255

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 246](http://ci.infinispan.org/viewLog.html?buildId=40614&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 1cc89ea9454c8ba765f97c785132f4e1be7a23e8
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:12:19

**Comment by mgencur** [comment]
Hi Vittorio, could you integrate the test suite refactoring first? This PR depends on #72 and it depends on #74 in turn. Without them I can't verify this this PR works fine.

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 256](http://ci.infinispan.org/viewLog.html?buildId=40883&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 1cc89ea9454c8ba765f97c785132f4e1be7a23e8
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:13:51

**Comment by mgencur** [comment]
This PR was already integrated. The commit is in master branch.

**Pull request closed without merging**
