### PR TITLE
HRCPP-268 Upgrade Narayana version in the Java test suite

### PR DESCRIPTION
**Pull request by mgencur**
https://issues.jboss.org/browse/HRCPP-268

### CODE REVIEW

**Comment by infinispanrelease** [comment]
Started - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 194](http://ci.infinispan.org/viewLog.html?buildId=39767&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for a9994e500d89af75dc93802e1ea24f0cb551a67b

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 194](http://ci.infinispan.org/viewLog.html?buildId=39767&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for a9994e500d89af75dc93802e1ea24f0cb551a67b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:19:59

**Comment by tristantarrant** [comment]
Pushed to master, thanks

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 212](http://ci.infinispan.org/viewLog.html?buildId=39983&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for a9994e500d89af75dc93802e1ea24f0cb551a67b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:14:12

**Pull request closed without merging**
