### PR TITLE
Tests for remote script execution

### PR DESCRIPTION
**Pull request by mgencur**
Additional test for remote execution of distributed streams. It includes macbeth.txt which is used by the map/reduce job. This file is a little longer:)

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 257](http://ci.infinispan.org/viewLog.html?buildId=41279&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 672e7311a49bea98d53b65cdf41170856f225f5c
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:16:04

**Comment by mgencur** [comment]
Added one more file that I forgot to commit.

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 258](http://ci.infinispan.org/viewLog.html?buildId=41306&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for d7e7265de3bf741e225e6074339f4bc7b842082b
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:16:25

**Comment by rigazilla** [comment]
pushed thanks

**Pull request merged**
