### PR TITLE
HRCPP-389 Remove expected failures from the Java test suite

### PR DESCRIPTION
**Pull request by mgencur**
https://issues.jboss.org/browse/HRCPP-389

Depends on https://issues.jboss.org/browse/ISPN-8077

### CODE REVIEW

**Comment by mgencur** [comment]
Could you take a look at this PR please?

**Comment by rigazilla** [comment]
the CI build fails with this PR: [jenkins](http://ci.infinispan.org/job/Infinispan%20C%20Sharp%20Client/view/change-requests/job/PR-119/)

We probably need to update the java test to 9.1.0.Final (java_test/pom.xml)

**Comment by mgencur** [comment]
I did the upgrade. Let's see what CI tells about the PR. I have some failures locally which are related to exhausted TCP ports.

**Comment by mgencur** [comment]
OK. So there are the same failures as on my local Windows 7 in VM: java.lang.AssertionError: java.net.BindException: Only one usage of each socket address (protocol/network address/port) is normally permitted
This is related to dynamic allocation of ports in ServerTestingUtil. The tests are not able to allocated any ports so they all run on the same port. I will look into this.

**Comment by mgencur** [comment]
I've created this one: https://issues.jboss.org/browse/ISPN-8333
Will create a PR for it shortly. But it means we'll need to wait for Infinispan 9.1.2  :(

**Pull request closed without merging**
