### PR TITLE
HRCPP-273 added missing proto2 files

### PR DESCRIPTION
**Pull request by rigazilla**
Added the missing files, updated the .proj to put the file into the working dir of the executable

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 204](http://ci.infinispan.org/viewLog.html?buildId=39910&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for d820a7ddfde3a4c495429f750f124ce6ffbbf04f
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:01

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 215](http://ci.infinispan.org/viewLog.html?buildId=39989&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for d820a7ddfde3a4c495429f750f124ce6ffbbf04f
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:49

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 216](http://ci.infinispan.org/viewLog.html?buildId=39990&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for d820a7ddfde3a4c495429f750f124ce6ffbbf04f
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:14:10

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 219](http://ci.infinispan.org/viewLog.html?buildId=40055&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for d820a7ddfde3a4c495429f750f124ce6ffbbf04f
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:14:10

**Comment by mgencur** [comment]
Vittorio, I think this is incorporated in #74 . In other words, I haven't seen any missing proto files. They were in a different location and I moved them to the correct one. Would you mind if we close this and rather integrate #74 which refactors the test suite?

**Comment by rigazilla** [comment]
Martin, I will apply #74 before this PR so we can see the delta between #72  and the new head and we can decide.

**Comment by mgencur** [comment]
Great. Thanks.

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 240](http://ci.infinispan.org/viewLog.html?buildId=40548&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for d820a7ddfde3a4c495429f750f124ce6ffbbf04f
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:13:51

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 252](http://ci.infinispan.org/viewLog.html?buildId=40859&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for d820a7ddfde3a4c495429f750f124ce6ffbbf04f
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:14:56

**Comment by mgencur** [comment]
This one is now included in #74. I used the files to fix the failing query test. Thanks Vittorio. I'm closing this one.

**Pull request closed without merging**
