### PR TITLE
Hrcpp 357/customevents

### PR DESCRIPTION
**Pull request by rigazilla**
Support, api and test for custom events.
Fix for https://issues.jboss.org/browse/HRCPP-357

### CODE REVIEW

**Comment by mgencur** [comment]
@rigazilla , there's a build problem.

**Comment by rigazilla** [comment]
@mgencur looking into. path name too long for windows

**Comment by mgencur** [comment]
Now that I closed https://github.com/infinispan/dotnet-client/pull/108, can this one be closed too?

**Comment by rigazilla** [comment]
ok @mgencur  this can be closed

**Comment by mgencur** [comment]
Closing.

**Pull request closed without merging**
