### PR TITLE
HRCPP-270 Updated README.txt info

### PR DESCRIPTION
**Pull request by rigazilla**
Updated readme information

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 197](http://ci.infinispan.org/viewLog.html?buildId=39784&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 638617ab24ceb99550145a624dd3131dc52ca3b4
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:18:42

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 214](http://ci.infinispan.org/viewLog.html?buildId=39985&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 638617ab24ceb99550145a624dd3131dc52ca3b4
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:14:13

**Comment by mgencur** [comment]
Pushed. Thanks

**Comment by infinispanrelease** [comment]
**UNKNOWN** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 228](http://ci.infinispan.org/viewLog.html?buildId=40510&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 638617ab24ceb99550145a624dd3131dc52ca3b4
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:01:06

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 229](http://ci.infinispan.org/viewLog.html?buildId=40514&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 638617ab24ceb99550145a624dd3131dc52ca3b4
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:29

Process exited with code 1

**Pull request closed without merging**
