### PR TITLE
HRCPP-396 More negative tests for Authentication

### PR DESCRIPTION
**Pull request by mgencur**
* also re-enable tests after fixing HRCPP-384 and HRCPP-388

https://issues.jboss.org/browse/HRCPP-396

### CODE REVIEW

**Comment by mgencur** [comment]
Can you integrate this, please?

**Comment by rigazilla** [comment]
Build fails on CI: [jenkins](http://ci.infinispan.org/job/Infinispan%20C%20Sharp%20Client/view/change-requests/job/PR-123/)

**Comment by mgencur** [comment]
The failure doesn't seem to be related to my changes. The only failure I see is in the NearCacheEvictionTest which I don't touch. Do you see other errors that might be related? Thanks

**Comment by rigazilla** [comment]
I launched the build again, now it looks okay.
Code look good to me

**Comment by rigazilla** [comment]
merged, thanks

**Pull request merged**
