### PR TITLE
HRCPP-267 Build only for a specific bitness (64 default)

### PR DESCRIPTION
**Pull request by rigazilla**
Simplified build.

### CODE REVIEW

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 193](http://ci.infinispan.org/viewLog.html?buildId=39764&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for a5a3d42759199f572db1c5c9f7b8ed3404b02920
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:19:07

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 199](http://ci.infinispan.org/viewLog.html?buildId=39859&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 16ceb3ab0ffefa2263bb698d25d02915b1138476
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:13:23

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 200](http://ci.infinispan.org/viewLog.html?buildId=39863&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 16ceb3ab0ffefa2263bb698d25d02915b1138476
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:10:58

Process exited with code 1

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 201](http://ci.infinispan.org/viewLog.html?buildId=39864&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for e02c073abdea40742273195bf0f1b30bc7d1aa7c
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:02

Process exited with code 1

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 202](http://ci.infinispan.org/viewLog.html?buildId=39870&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 4a5444b574e05de93822ffbe3d3b5bc6abcda794
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:44

Process exited with code 1

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 203](http://ci.infinispan.org/viewLog.html?buildId=39873&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 4a5444b574e05de93822ffbe3d3b5bc6abcda794
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:11

Process exited with code 1

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 205](http://ci.infinispan.org/viewLog.html?buildId=39925&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 22ecf1c580c406d01e8723c8954874e773dbebff
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:08:22

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 206](http://ci.infinispan.org/viewLog.html?buildId=39950&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for f94c372e0fd74723de81d31bf6a72b0bd0dc03ef
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:11:34

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 207](http://ci.infinispan.org/viewLog.html?buildId=39952&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for f1fa20870be4b9aeb5e14d7dae22f46c782023b0
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:12:14

**Comment by infinispanrelease** [comment]
**FAILURE** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 208](http://ci.infinispan.org/viewLog.html?buildId=39963&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 4a973bcfaa276d603fd41f7729c0f27754969403
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:07:55

Process exited with code 1

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 209](http://ci.infinispan.org/viewLog.html?buildId=39965&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 4a973bcfaa276d603fd41f7729c0f27754969403
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:14:02

**Comment by tristantarrant** [comment]
Pushed to master, thanks

**Comment by infinispanrelease** [comment]
**SUCCESS** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 211](http://ci.infinispan.org/viewLog.html?buildId=39982&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 4a973bcfaa276d603fd41f7729c0f27754969403
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:14:12

**Pull request closed without merging**
