### PR TITLE
JDG-203 Removed old Serializer classes

### PR DESCRIPTION
**Pull request by rigazilla**
replaced Serializer architecture with the new Marshaller arch.

### CODE REVIEW

**Comment by infinispanrelease** [comment]
Started - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 195](http://ci.infinispan.org/viewLog.html?buildId=39772&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 1cc89ea9454c8ba765f97c785132f4e1be7a23e8

**Comment by infinispanrelease** [comment]
**UNKNOWN** - TeamCity HotRod C# Client :: Pull requests monitor - WIN_S2012 [Build 195](http://ci.infinispan.org/viewLog.html?buildId=39772&buildTypeId=HotRodCSharp_PullRequestsMonitorWinS2012&guest=1) for 1cc89ea9454c8ba765f97c785132f4e1be7a23e8
Tests: 0, 0 failed (0 new), 0 ignored. Build time: 00:05:55

Process exited with code 1

**Comment by mgencur** [comment]
Hi Vittorio, do you think this PR should be sent to the upstream client now? Or do we plan to remove the obsolete classes later? Thanks

**Comment by rigazilla** [comment]
Hi Martin, I closed this PR because I created it with a wrong name (JDG). The correct one is this
https://github.com/infinispan/dotnet-client/pull/70

I would like to get this PR integrate soon, but I have to update the CI build before.
You'd like to check it and leave a comment if all sounds good to you? So we can speed up the process?
Thank you

**Pull request closed without merging**
